; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
build_cache_dir = ./.pio/build_cache

[env:ESP32_S3_wroom]
platform = espressif32
board = ESP32_S3_wroom_1
framework = espidf
board_build.partitions = partitions/partitions.csv
board_build.filesystem = littlefs
board_build.sdkconfig_defaults = sdkconfig.defaults
lib_deps = 
    https://github.com/joltwallet/esp_littlefs.git

monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1

build_flags = ; LittleFS configuration
    -DCONFIG_LITTLEFS_CACHE_SIZE=512
    -DCONFIG_LITTLEFS_BLOCK_SIZE=4096
    -DCONFIG_LITTLEFS_READ_SIZE=256
    -DCONFIG_LITTLEFS_WRITE_SIZE=256
    -DCONFIG_LITTLEFS_LOOKAHEAD_SIZE=128
    -DCONFIG_LITTLEFS_MAX_PARTITIONS=1
    -DCONFIG_LITTLEFS_BLOCK_CYCLES=512
    -DCONFIG_LITTLEFS_PAGE_SIZE=256